### ISSUE TITLE
感谢参加EveryMatrix机试题测试

### ISSUE THREAD

**Issue by wangjia184** [panpeng2018/2022#1]
你好，感谢参加EveryMatrix机试题测试。也感谢你特意截屏录制视频。

提交的代码中有如下问题：

1. https://github.com/panpeng2018/2022/blob/master/WebApplication1/Controllers/CustomController.cs#L60-L75
Customer集合初始状态应为空。`UpdateList`方法执行时，如果该用户不存在则应该新增并保存分数；否则应该修改已经存在用户的分数
2. 线程安全性。所有的外部接口在多线程环境下应该是安全的。不能因为同时发生的调用导致不可预知的后果。
3. https://github.com/panpeng2018/2022/blob/master/WebApplication1/Controllers/CustomController.cs#L81
性能。需要考虑Customer集合中数据量很多的情况，比如十万级别，百万级别。在查询和维护该数据结构时都需要考量时间复杂度。同时也需要考虑到多用户同时查询或修改。

该试题的Non-functional requirements中写到
> 1. No persistence nor database is required. State in memory only.
> 2. Only use .Net Core. Do not use external frameworks/assemblies, except maybe for testing.
> 3. The service needs to be able to handle lots of simultaneous requests, so bear in mind the memory and CPU resources at your disposal.

其中最重要的是第三点。该试题需求虽然是一个很简单的问题，但考察的是开发中最基本的数据结构/算法/线程安全性等问题。更深层次的，考察的是开发者对“优良”代码的追求。

如果你乐意，可以尝试改进并再次提交。

谢谢。

**Comment by panpeng2018** [comment]
感谢指导 找时间 加固一下代码。

**Comment by panpeng2018** [comment]
> 你好，感谢参加EveryMatrix机试题测试。也感谢你特意截屏录制视频。
> 
> 提交的代码中有如下问题：
> 
> 1. https://github.com/panpeng2018/2022/blob/master/WebApplication1/Controllers/CustomController.cs#L60-L75
>    Customer集合初始状态应为空。`UpdateList`方法执行时，如果该用户不存在则应该新增并保存分数；否则应该修改已经存在用户的分数
> 2. 线程安全性。所有的外部接口在多线程环境下应该是安全的。不能因为同时发生的调用导致不可预知的后果。
> 3. https://github.com/panpeng2018/2022/blob/master/WebApplication1/Controllers/CustomController.cs#L81
>    性能。需要考虑Customer集合中数据量很多的情况，比如十万级别，百万级别。在查询和维护该数据结构时都需要考量时间复杂度。同时也需要考虑到多用户同时查询或修改。
> 
> 该试题的Non-functional requirements中写到
> 
> > 1. No persistence nor database is required. State in memory only.
> > 2. Only use .Net Core. Do not use external frameworks/assemblies, except maybe for testing.
> > 3. The service needs to be able to handle lots of simultaneous requests, so bear in mind the memory and CPU resources at your disposal.
> 
> 其中最重要的是第三点。该试题需求虽然是一个很简单的问题，但考察的是开发中最基本的数据结构/算法/线程安全性等问题。更深层次的，考察的是开发者对“优良”代码的追求。
> 
> 如果你乐意，可以尝试改进并再次提交。
> 
> 谢谢。

已经加固了，麻烦大佬帮忙看看。

**Comment by wangjia184** [comment]
没有什么很大的不同。

代码依旧不是线程安全的，即使换用了`ConcurrentBag`

```
public static bool UpdateList(Int64 customerid, decimal score)
        {
            try
            {
                var model = list.Where(c => c.CustomerID == customerid).FirstOrDefault();
                if (model != null)
                {
                    model.Score = model.Score+score;
                }
                else
                {
                    Customer cmd = new Customer();
                    cmd.CustomerID = customerid;
                    cmd.Score = score;
                    list.Add(cmd);
                }
                return true;
            }
            catch
            {
                return false;
            }
        }
```

* 比如这段，不同的请求很可能会同时拿到同一个`model`，同时对它进行修改，产生不可预知的结果
* 又或者对于相同的customerid会添加多个实例`Customer`到集合中
* 貌似对线程安全有什么误解，特意加上`try-catch`尝试去捕获异常，且不记录异常。实际上线程安全违例的时候，很多情况下是没有异常的，只是结果错了。

**Comment by panpeng2018** [comment]
> 没有什么很大的不同。
> 
> 代码依旧不是线程安全的，即使换用了`ConcurrentBag`
> 
> ```
> public static bool UpdateList(Int64 customerid, decimal score)
>         {
>             try
>             {
>                 var model = list.Where(c => c.CustomerID == customerid).FirstOrDefault();
>                 if (model != null)
>                 {
>                     model.Score = model.Score+score;
>                 }
>                 else
>                 {
>                     Customer cmd = new Customer();
>                     cmd.CustomerID = customerid;
>                     cmd.Score = score;
>                     list.Add(cmd);
>                 }
>                 return true;
>             }
>             catch
>             {
>                 return false;
>             }
>         }
> ```
> 
> * 比如这段，不同的请求很可能会同时拿到同一个`model`，同时对它进行修改，产生不可预知的结果
> * 又或者对于相同的customerid会添加多个实例`Customer`到集合中
> * 貌似对线程安全有什么误解，特意加上`try-catch`尝试去捕获异常，且不记录异常。实际上线程安全违例的时候，很多情况下是没有异常的，只是结果错了。

加了一个普通锁

**Comment by wangjia184** [comment]
对于性能的理解似乎也有些许偏差。在初始化阶段用并行化`Parallel`加速填充该集合。先且不论这部分代码里面的两个线程安全的bug。并行化对某项工作进行加速，本质上是多线程或者多核将任务分解成同时执行的方式缩短总时间，但不能超过该任务最大阿姆达尔加速比，且计算机的运算量并没有降低。

对于该机试题，改进性能优先要考虑的是减少计算机的工作量，或者说降低复杂度，尤其是时间复杂度。

```
public static ConcurrentBag<CustomerExt> GetList(int customerid,int start, int end)
        {
            ConcurrentBag<CustomerExt> newlist = new ConcurrentBag<CustomerExt>();
            try
            {
                var listz = list.OrderByDescending(a => a.Score).ThenBy(a => a.CustomerID).ToList();
                var index = listz.FindIndex(u=>u.CustomerID== customerid);
                var lists = listz.GetRange(index - start, start + start+1);
                var i = start;
                foreach (var item in lists)
                {
                    CustomerExt cmd = new CustomerExt();
                    cmd.CustomerID = item.CustomerID;
                    cmd.Score = item.Score;
                    cmd.Rank = i;
                    i++;
                    newlist.Add(cmd);
                }
                return newlist;
            }
            catch
            {
                return newlist;
            }
        }
```

比如此方法中。Linq的 `OrderBy` 虽然是快排，时间复杂度是 `O(log(n))`，但每次都要重排整个集合到一个新的list。当集合数量很大后（比如十万），时间复杂度中的常数项将会达到一个难以忽略的程度。而且每次都需要重新allocate一个新的list数量也是十万，那么空间复杂度就有`O(n)`.  接下来的 `FindIndex`是一个时间复杂度 `O(n)`的操作。这段代码的总体时间复杂度就会很糟糕。

正确的做法应该是选取和利用合适的数据结构，在线程安全的前提下保证操作和维护该集合的复杂度尽量小。

* 如果利用dotnet类库中的类进行组合，大概可以做到查询`O(log(n))`, 维护`O(n)`，无法并发
* 如果是自己编写某数据结构，大概可以做到查询`O(log(n))`, 维护`O(log(n))`。甚至可以在该数据结构的基础上实现lockless

虽然这个机试题是个简单的问题，但要做到极致却很有讲究。因为看到你特意录制截屏，能看出你是个用心之人。我多说了几句，如有冒犯望谅解。
之后不会再关于该问题回复了。谢谢。

**Comment by panpeng2018** [comment]
这里我测试了下  50万条数据  新增 或者更新都是比较快的。 可能高并发的 多人调用接口  保证数据 一致性上要处理  假如是 正式的开发 我会运用  消息队列跟 redis缓存 进来。   感谢指点 你对代码追求比我高。  我是能用轮子就用轮子。

**Comment by panpeng2018** [comment]
在50万数据的前提下  我 测试了下 新增 更新 查询 都是极快的相应速度。

**Comment by panpeng2018** [comment]
500万数据 新增大概3S   更新一样的很快     但是查询 明显慢下来了

**Comment by wangjia184** [comment]
1毫秒 = 10^-3秒
3GHz CPU每核心每秒3x10^9个时钟周期。 
由于超级流水线技术，可以初略估计为平均一个周期执行一条指令。因此1毫秒大概可以执行3x10^6个指令周期，也就是说一毫秒内每核心可以执行300万条指令。

我们的产品对性能的要求很苛刻，目前能够在峰值吞吐率10000RPS下做到毫秒级响应。要求开发人员了解自己所写每一句代码的背后的成本。非有意为难，这个岗位可能并不适合你。
![image](https://user-images.githubusercontent.com/2765840/180594501-9d542c58-868d-4415-81cd-b5256d670976.png)

再次感谢你能够参与测试。

**Comment by panpeng2018** [comment]
谢谢指导~ 以后写代码 多注意下 线程 还有充分考虑CPU的性能。  去不去贵公司看缘分 不必强求。
可能我平常开发 对业务比较重 对性能 要求低  我最近都是JAVA+VUE开发
如果我接触几个 对性能有严苛要求的项目  估计会提升起来。
